# Vmamba (Mamber32) x1 image enhancement - Underwater (UIEB)
name: train_Vmamba_x1_underwater_0201
model_type: VmambaModel
scale: 1
num_gpu: auto
manual_seed: 0

datasets:
  train:
    name: UnderwaterTrain
    type: PairedImageDataset
  dataroot_gt: /data/wa/dataset/low_vision_task/UIE/A_data_spil/UIEB_09/reference-800
  dataroot_lq: /data/wa/dataset/low_vision_task/UIE/A_data_spil/UIEB_09/raw-800
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 64
    use_hflip: true
    use_rot: true

    num_worker_per_gpu: 0
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: UnderwaterVal
    type: PairedImageDataset
    dataroot_gt: /data/wa/dataset/low_vision_task/UIE/A_data_spil/UIEB_09/reference-90
    dataroot_lq: /data/wa/dataset/low_vision_task/UIE/A_data_spil/UIEB_09/raw-90
    filename_tmpl: '{}'
    io_backend:
      type: disk
    gt_size: 64

network_g:
  type: Mamber32
  upscale: 1
  in_chans: 3
  img_size: 128
  img_range: 1.

  embed_dim: 24
  d_state: 4
  depths: [1, 1, 1, 1]
  num_heads: [2, 2, 2, 2]
  window_size: 8
  inner_rank: 16
  num_tokens: 32
  convffn_kernel_size: 3
  mlp_ratio: 1.0
  upsampler: ~
  resi_connection: '1conv'

path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

train:
  use_amp: true
  optim_g:
    type: AdamW
    lr: !!float 4e-4
    weight_decay: !!float 1e-4
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [100000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 100000
  warmup_iter: -1

  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  # Disable extra losses to save memory
  ssim_opt: ~
  perceptual_opt: ~

val:
  val_freq: 2000
  save_img: false
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

logger:
  print_freq: 100
  save_checkpoint_freq: 200
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

dist_params:
  backend: nccl
  port: 29500
