# Restormer image restoration - Hazy (RESIDE/SOTS)
name: train_Restormer_x1_hazy_0201
model_type: RestormerModel
scale: 1
num_gpu: auto
manual_seed: 0

datasets:
  train:
    name: HazyTrain
    type: RESIDEDataset
    dataroot_gt: /data/wa/dataset/low_level_visual/reside/clear
    dataroot_lq: /data/wa/dataset/low_level_visual/reside/hazy
    meta_info_file: ~
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 96
    use_hflip: true
    use_rot: true

    num_worker_per_gpu: 6
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val_1:
    name: SOTS_indoor
    type: RESIDEDataset
    dataroot_gt: /data/wa/dataset/low_level_visual/reside/SOTS/indoor/gt
    dataroot_lq: /data/wa/dataset/low_level_visual/reside/SOTS/indoor/hazy
    filename_tmpl: '{}'
    io_backend:
      type: disk
    gt_size: 96

  val_2:
    name: SOTS_outdoor
    type: RESIDEDataset
    dataroot_gt: /data/wa/dataset/low_level_visual/reside/SOTS/outdoor/gt
    dataroot_lq: /data/wa/dataset/low_level_visual/reside/SOTS/outdoor/hazy
    filename_tmpl: '{}'
    io_backend:
      type: disk
    gt_size: 96

network_g:
  type: Restormer
  inp_channels: 3
  out_channels: 3
  dim: 48
  num_blocks: [4, 6, 6, 8]
  num_refinement_blocks: 4
  heads: [1, 2, 4, 8]
  ffn_expansion_factor: 2.66
  bias: false
  LayerNorm_type: WithBias
  dual_pixel_task: false

path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

train:
  ema_decay: 0.999
  optim_g:
    type: AdamW
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [100000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 100000
  warmup_iter: -1

  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

val:
  val_freq: 200
  save_img: false
  window_size: 8  # pad to multiple of 8 to satisfy Restormer downsampling
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
    # uiqm:
    #   type: calculate_uiqm
    # uciqe:
    #   type: calculate_uciqe
    entropy:
      type: calculate_entropy
    lpips:
      type: calculate_lpips
      net_type: vgg
      better: lower
    niqe:
      type: calculate_niqe
      crop_border: 0
      better: lower

logger:
  print_freq: 100
  save_checkpoint_freq: 2000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

dist_params:
  backend: nccl
  port: 29500
