# GENERATE TIME: Tue Jan 20 12:05:27 2026
# CMD:
# basicsr/train.py -opt options/train/underwater/train_mamba_water_stage2_soat.yml

# Stage 2: UIEB Cleaned 微调
name: MambaWater_Stage2_SOTA_0119
model_type: MambaWaterModel
scale: 1
num_gpu: 1
manual_seed: 10

datasets:
  train:
    name: UIEB_Cleaned
    type: PairedImageDataset
    # 指向你清洗后的 UIEB 路径
  dataroot_gt: /data/wa/dataset/low_vision_task/UIE/A_data_spil/UIEB_09/reference-800
  dataroot_lq: /data/wa/dataset/low_vision_task/UIE/A_data_spil/UIEB_09/raw-800
    
    io_backend:
      type: disk

    gt_size: 128
    use_hflip: true
    use_rot: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 4 # 微调时稳一点

  val:
    name: UIEB_Val
    type: PairedImageDataset
    dataroot_gt: /data/wa/dataset/low_vision_task/UIE/A_data_spil/UIEB_09/reference-90
    dataroot_lq: /data/wa/dataset/low_vision_task/UIE/A_data_spil/UIEB_09/raw-90
    io_backend:
      type: disk

network_g:
  type: MambaWater
  upscale: 1
  in_chans: 3
  img_size: 128
  img_range: 1.
  embed_dim: 40
  d_state: 16
  depths: [2, 2, 2, 2]
  num_heads: [4, 4, 4, 4]
  window_size: 16
  inner_rank: 32
  num_tokens: 64
  convffn_kernel_size: 3
  mlp_ratio: 1.2
  resi_connection: '1conv'

path:
  # 使用绝对路径，避免从不同工作目录运行时找不到文件
  pretrain_network_g: /data/wa/work/BasicSR/experiments/MambaWater_Stage1_Pretrain_0118/models/net_g_23500.pth
  strict_load_g: true
  resume_state: /data/wa/work/BasicSR/experiments/MambaWater_Stage2_SOTA_0119/training_states/74000.state

train:
  optim_g:
    type: AdamW
    lr: !!float 2e-4
    weight_decay: !!float 1e-4
    betas: [0.9, 0.99]

  scheduler:
    # 【关键修改 1】: 去掉 Restart，改为单周期 Cosine
    # 我们只跑一轮完整的下降，让模型在结束时刚好收敛到最优
    type: CosineAnnealingRestartLR
    
    # 【关键修改 2】: periods 必须等于 total_iter
    # 这样学习率会在 15万步时刚好降到最低点 (1e-7)，强迫模型收敛
    periods: [150000] 
    
    restart_weights: [1]
    eta_min: !!float 1e-7

  # 【关键修改 3】: 总步数减半
  # 15万步对于 700张图的微调来说，已经是 700+ 个 Epoch 了，绝对足够
  total_iter: 150000
  warmup_iter: -1

  # Stage 2: 纯净刷分 (关掉 VGG, 只用 Charbonnier + SSIM)
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    eps: !!float 1e-3
  
  ssim_opt:
    type: SSIMLoss
    loss_weight: 0.2

val:
  val_freq: 500
  save_img: false
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
    # 水下色彩衡量指标
    uiqm:
      type: calculate_uiqm
    uciqe:
      type: calculate_uciqe
    # 信息墒
    entropy:
      type: calculate_entropy
    # 感知与自然指标  
    lpips:
      type: calculate_lpips
      net_type: vgg
      better: lower
    niqe:
        type: calculate_niqe
        crop_border: 0
        better: lower
logger:
  print_freq: 100
  save_checkpoint_freq: 500
  use_tb_logger: true