# GENERATE TIME: Tue Dec 30 11:26:49 2025
# CMD:
# basicsr/train.py -opt options/train/underwater/train_mambawater_1.yml

name: MambaWater_UIEB_enhance0102_4
model_type: MambaWaterModel
scale: 1
num_gpu: 1
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    task: Restoration
    name: UIEB
    type: PairedImageDataset
    dataroot_gt: /data/wa/dataset/UIEB_09/reference-800
    dataroot_lq: /data/wa/dataset/UIEB_09/raw-800
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 2
    prefetch_mode: ~

  val:
    name: UIEB
    type: PairedImageDataset
    dataroot_gt: /data/wa/dataset/UIEB_800/reference-90
    dataroot_lq: /data/wa/dataset/UIEB_800/raw-90
    filename_tmpl: '{}'
    io_backend:
      type: disk
    gt_size: 128



# network_g:
#   type: MambaWater
#   upscale: 1
#   in_chans: 3
#   img_size: 128
#   img_range: 1.

#   embed_dim: 32        # 由 48 → 32，显存下降 ~50%
#   d_state: 8
#   depths: [2, 2, 2, 2] # 由 [5,5,5,5] 大幅缩小
#   num_heads: [2, 2, 2, 2]
#   window_size: 8       # 由 16 → 8，显存立刻减少 4 倍
#   inner_rank: 16       # 降低 Mamba 内部维度
#   num_tokens: 32       # 由 64 → 32（attention 显存砍半）

#   convffn_kernel_size: 3
#   mlp_ratio: 0.5
#   upsampler: ~
#   resi_connection: '1conv'

network_g:
  type: MambaWater
  upscale: 1
  in_chans: 3
  img_size: 128
  img_range: 1.

  embed_dim: 48        # 从32提升到48已经有很大提升，60对GPU不友好
  d_state: 16          # 保持 16，这对 Mamba 性能很关键
  depths: [2, 4, 4, 2] # 相比 [4,4,4,4] 减少了 4 层，但保留了深层特征提取能力
  num_heads: [4, 4, 4, 4] # 48/4 = 12 dim per head
  window_size: 16      # 保持 16，大感受野很重要
  inner_rank: 32
  num_tokens: 64
  convffn_kernel_size: 3
  mlp_ratio: 1.5       # 2.0 -> 1.5。1.5 已经比 0.5 强很多，能显著降低显存峰值
  
  upsampler: ~
  resi_connection: '1conv'


# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  use_amp: true   
  
  optim_g:
    type: Adam
    #lr: !!float 2e-4
    lr: !!float 5e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    # milestones: [250000, 400000, 450000, 475000]
    milestones: [8000, 12000, 14000]
    gamma: 0.5

  total_iter: 15000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0

  ssim_opt:
    type: SSIMLoss
    loss_weight: 0.2

# validation settings
val:
  val_freq: 200
  save_img: false

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0



# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: 200
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500