# Stage 2: UIEB Cleaned 微调
name: MambaWater_Stage3_SOTA_0121_polish10k
model_type: MambaWaterModel
scale: 1
num_gpu: 1
manual_seed: 10

datasets:
  train:
    name: UIEB_Cleaned
    type: PairedImageDataset
    # 指向你清洗后的 UIEB 路径
    dataroot_gt: /data/wa/dataset/Cleand_uie_data/Cleaned_UIEB/split/train/reference
    dataroot_lq: /data/wa/dataset/Cleand_uie_data/Cleaned_UIEB/split/train/raw
    
    io_backend:
      type: disk

    gt_size: 128
    use_hflip: true
    use_rot: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 4 # 微调时稳一点

  val:
    name: UIEB_Val
    type: PairedImageDataset
    dataroot_gt: /data/wa/dataset/Cleand_uie_data/Cleaned_UIEB/split/val/reference
    dataroot_lq: /data/wa/dataset/Cleand_uie_data/Cleaned_UIEB/split/val/raw
    io_backend:
      type: disk

network_g:
  type: MambaWater
  upscale: 1
  in_chans: 3
  img_size: 128
  img_range: 1.
  embed_dim: 40
  d_state: 16
  depths: [2, 2, 2, 2]
  num_heads: [4, 4, 4, 4]
  window_size: 16
  inner_rank: 32
  num_tokens: 64
  convffn_kernel_size: 3
  mlp_ratio: 1.2
  resi_connection: '1conv'

path:
  pretrain_network_g: experiments/MambaWater_Stage2_SOTA_0119/models/net_g_61500.pth
  strict_load_g: true
  resume_state: experiments/MambaWater_Stage2_SOTA_0119/training_states/61500.state

train:
  optim_g:
    type: AdamW
    lr: !!float 5e-5
    weight_decay: !!float 1e-4
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [10000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 10000
  warmup_iter: 1000

  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    eps: !!float 1e-3
  
  ssim_opt:
    type: SSIMLoss
    loss_weight: 0.2

val:
  val_freq: 500
  save_img: false
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
    # 水下色彩衡量指标
    uiqm:
      type: calculate_uiqm
    uciqe:
      type: calculate_uciqe
    # 信息墒
    entropy:
      type: calculate_entropy
    # 感知与自然指标  
    lpips:
      type: calculate_lpips
      net_type: vgg
      better: lower
    niqe:
        type: calculate_niqe
        crop_border: 0
        better: lower
logger:
  print_freq: 100
  save_checkpoint_freq: 500
  use_tb_logger: true