# Stage 1: LSUI + UFO 联合预训练
name: MambaWater_Stage1_Pretrain_0118
model_type: MambaWaterModel
scale: 1
num_gpu: 2
manual_seed: 10

datasets:

  train: # 名字无所谓，关键是结构
    name: Mix_LSUI_UFO
    type: PairedImageDataset
    # 指向你合并后的文件夹
    dataroot_gt: /data/wa/dataset/Cleand_uie_data/Cleaned_Stage1_Pretrain/ref
    dataroot_lq: /data/wa/dataset/Cleand_uie_data/Cleaned_Stage1_Pretrain/raw
    
    io_backend:
      type: disk
    gt_size: 128
    use_hflip: true
    use_rot: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 6

  val:
    name: UIEB_Val
    type: PairedImageDataset
    dataroot_gt: /data/wa/dataset/Cleand_uie_data/Cleaned_UIEB/split/val/reference
    dataroot_lq: /data/wa/dataset/Cleand_uie_data/Cleaned_UIEB/split/val/raw
    io_backend:
      type: disk

network_g:
  type: MambaWater
  upscale: 1
  in_chans: 3
  img_size: 128
  img_range: 1.
  embed_dim: 40
  d_state: 16
  depths: [2, 2, 2, 2]
  num_heads: [4, 4, 4, 4]
  window_size: 16
  inner_rank: 32
  num_tokens: 64
  convffn_kernel_size: 3
  mlp_ratio: 1.2
  resi_connection: '1conv'

path:
  pretrain_network_g: ~
  strict_load_g: true

train:
  optim_g:
    type: AdamW
    lr: !!float 4e-4
    weight_decay: !!float 1e-4
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [150000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 150000
  warmup_iter: -1

  # Stage 1: 必须开感知损失，为了学结构
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    eps: !!float 1e-3
  
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      'conv5_4': 1.0
    vgg_type: vgg19
    use_input_norm: true
    range_norm: false
    perceptual_weight: 0.1
    criterion: l1

val:
  val_freq: 500
  save_img: false
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 0
    ssim:
      type: calculate_ssim
      crop_border: 0

logger:
  print_freq: 100
  save_checkpoint_freq: 500
  use_tb_logger: true