name: sanity_test_MambaIRv2
model_type: MambaIRv2Model
scale: 1
num_gpu: 1
manual_seed: 123

datasets:
  train:
    name: UIEB_train
    type: PairedImageDataset
    dataroot_gt: /data/wa/dataset/UIEB/reference-890
    dataroot_lq: /data/wa/dataset/UIEB/raw-890
    io_backend:
      type: disk

    use_hflip: false
    use_rot: false

    gt_size: 64                # ★超小图检测模式
    batch_size_per_gpu: 1      # ★不会 OOM
    use_shuffle: true
    num_worker_per_gpu: 2
    prefetch_mode: ~

  # val:
  #   name: UIEB_val
  #   type: PairedImageDataset
  #   dataroot_gt: /data/wa/dataset/tiny_val/gt
  #   dataroot_lq: /data/wa/dataset/tiny_val/lq
  #   io_backend:
  #     type: disk
  #   filename_tmpl: '{}'

network_g:
  type: MambaIRv2
  upscale: 1
  in_chans: 3
  img_size: 64
  img_range: 1.
  embed_dim: 32               # ★最小模型
  d_state: 8
  depths: [1, 1]              # ★两个 block
  num_heads: [2, 2]
  window_size: 8
  inner_rank: 16
  num_tokens: 16
  convffn_kernel_size: 3
  mlp_ratio: 2.

path:
  pretrain_network_g: ~
  strict_load_g: false
  resume_state: ~

train:
  use_amp: true

  optim_g:
    type: AdamW
    lr: 0.0002
    betas: [0.9, 0.99]
    weight_decay: 0.01

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [1000]
    restart_weights: [1]
    eta_min: 0.000001

  total_iter: 1000          # ★只跑 1000 iter 检测
  warmup_iter: 10

  pixel_opt:
    type: L1Loss
    loss_weight: 1.0

# 关闭昂贵的 SSIM + perceptual loss
#（逻辑调通后再打开）
val:
  val_freq: 200
  save_img: false

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

logger:
  print_freq: 20
  save_checkpoint_freq: 500
  use_tb_logger: false

dist_params:
  backend: nccl
  port: 29500
